spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

auth:
  google:
    base_url: ${GOOGLE_BASE_URL}
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_SECRET}
    redirect_url: ${GOOGLE_REDIRECT_URL}